version: "3.5"
services: 
  apache:
    #build: ./apache/.
    image: "vickyrv2206/apache:3.0"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    networks:
      - test_net
networks:
  test_net:
    name: test_net
    driver: overlay
  #default:
    #external:
     # name: sample_net
volumes:
  backup:
  
